### ISSUE TITLE
Export pop ups data to excel

### ISSUE THREAD

**Issue by Batchimegb** [erxes/erxes#1637] opened 2020-01-22 12:04 UTC

**Comment by munkhjin0223** [comment] 2020-02-08 08:21
Duplicate of #1674

**Comment by Mambatukaa** [comment] 2020-07-30 06:18
Hey there,
We've moved our enhancement/feature requests to https://roadmap.erxes.io
Please use this link in the future to submit your features.

Thank you.

**Closed by Mambatukaa** 2020-07-30 06:18 UTC
Labels: client, type: enhancement
