### ISSUE TITLE
Fix disabled object-literal-sort-keys ts rule

### ISSUE THREAD

**Issue by batamar** [erxes/erxes#617] opened 2018-10-05 11:19 UTC
- Split new branch from ts branch

**Comment by ItsMeWithTheFace** [comment] 2018-10-07 21:37
Hi @batamar, could I take on this issue if it hasn't been worked on yet?

**Comment by Mambatukaa** [comment] 2020-07-30 06:50
Hey there,

This issue is outdated or there is a more recent duplicate.
Closing this issue to keep the Issues less cluttered.

We've moved our enhancement/feature requests to https://roadmap.erxes.io.
Please use this link in the future to submit your features.

Thank you.

**Comment by KhongorzulD** [comment] 2021-11-01 18:49
It seems like the issue is already found its solution so I will close the issue if there's not anything that contradicts to it.

**Closed by KhongorzulD** 2021-11-01 18:49 UTC
Labels: help wanted, Hacktoberfest
