### ISSUE TITLE
INBOX > FILTER by DATE / NOT WORKING / UNfiltered conversations

### ISSUE THREAD

**Issue by Amura07** [erxes/erxes#4144] opened 2023-02-01 00:44 UTC

**Comment by mendorshikh** [comment] 2023-02-11 01:39
@Amura07 Please retest it on office. It works for me. Or record it using https://chrome.google.com/webstore/detail/jam/iohjgamcilhbgmhbnllfolmkmmekfmci

**Comment by Mambatukaa** [comment] 2023-02-11 10:33
@mendorshikh @Amura07 this issue is the duplicate of #4160.

**Closed** 2023-02-11 10:34 UTC
Labels: 🐛 bug, priority: High, Backlog
