### ISSUE TITLE
Can't write in the Team Inbox editor

### ISSUE THREAD

**Issue by Aditya231** [erxes/erxes#2346] opened 2020-10-01 13:39 UTC
Sometimes the ### text editor in the Conversations changes and the user can no longer type. Then the user needs to refresh the page to remove the error. This issue happens irregularly.

**Comment by daniloff200** [comment] 2020-10-01 21:28
looks like duplicate of #2318

**Comment by indraganzorig** [comment] 2020-10-02 05:06
Hi @Aditya231 this issue has been resolved, as @daniloff200 mentioned above.

**Closed by indraganzorig** 2020-10-02 05:06 UTC
